IF NOT EXISTS(SELECT 1 FROM sysobjects WHERE ID = OBJECT_ID('T_PRODUCT') AND Xtype = 'U')
BEGIN
	CREATE TABLE T_PRODUCT
	(
		PROD_NO INT PRIMARY KEY,
		NAME	NVARCHAR(32)
	)
	CREATE TABLE T_ORDER
	(
		ORDER_NO	INT			,
		PROD_NO		INT			,
		REG_DATE	DATETIME	,	
		QUANTITY	INT
	)

	IF NOT EXISTS(SELECT 1 FROM sys.sysindexes WHERE NAME = 'IDX_TORDER')
	BEGIN
		CREATE CLUSTERED INDEX IDX_TORDER ON T_ORDER(PROD_NO,REG_DATE)
	END

	DECLARE @I INT
	SELECT @I = 1

	INSERT INTO T_PRODUCT
	SELECT 1, N'PROD1'
	UNION ALL
	SELECT 2, N'PROD2'

	WHILE(@I<=100)
	BEGIN
		INSERT INTO T_ORDER
		SELECT @I, (@I % 2) + 1, DATEADD(MI, @I, '2018-12-16 00:00'), @I

		SELECT @I = @I + 1
	END
		
END

SELECT *
  FROM T_PRODUCT AS A
  JOIN 