# -*- coding: utf-8 -*-
"""Multiprocessing_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ifQvFsQQwXq9mDqqKYOf-1CLVQt2iZFn
"""

#MultiProcessing 미 사용
import time

starttime = time.time()

def count(name):
    for i in range(1,2000):
        print('name : {}'.format(i))

numlist = ['m1', 'm2', 'm3', 'm4']

for num in numlist:
    count(num)

print('--- %s sconds ---' % (time.time() - starttime))

#MultiProcessing 사용
import time
from multiprocessing import Pool

starttime = time.time()

def count(name):
    for i in range(1,2000):
        print('name : {}'.format(i))

numlist = ['m1', 'm2', 'm3', 'm4']

for num in numlist:
    count(num)


if __name__ == '__main__':
    #MutlProcessing Pool사용
    pool = Pool(processes=2) #프로세스 사용 개수
    pool.map(count, numlist)
    #메모리 누수 방지
    pool.close()
    pool.join()
    
print('--- %s sconds ---' % (time.time() - starttime))

