CREATE TABLE dbo.UserList
(
	UserSeq	BIGINT NOT NULL CONSTRAINT DF_UserList_UserSeq DEFAULT NEXT VALUE FOR UserList_UserSeq_NextValue --SEQUENCE DEFAULT Ãß°¡
,	UserType TINYINT NOT NULL CONSTRAINT DF_UserList_UserType DEFAULT(0)
,	UserName NVARCHAR(32) NOT NULL CONSTRAINT DF_UserList_UserName DEFAULT('')
,	CONSTRAINT PK_UserList PRIMARY KEY(UserSeq ASC)
)
